DMG_FALLOFF_SHOTGUN = 0.8
DMG_FALLOFF_SMG     = 0.9
DMG_FALLOFF_RIFLE   = 0.94
DMG_FALLOFF_SNIPER  = 0.98
DMG_FALLOFF_NONE    = 1

ACCURACY_POOR    = {16, 8}
ACCURACY_AVERAGE = {14, 6}
ACCURACY_GOOD    = {12, 4}
ACCURACY_GREAT   = {10, 2}
ACCURACY_PERFECT = {8, 1}
